const DEFAULT_EXERCISES=[
  {id:'e1',name:'Bench press',part:'Grudi'},
  {id:'e2',name:'Kosi bench press',part:'Grudi'},
  {id:'e3',name:'Čučnjevi',part:'Noge'},
  {id:'e4',name:'Mrtvo dizanje',part:'Leđa'},
  {id:'e5',name:'Potisak iznad glave',part:'Ramena'},
  {id:'e6',name:'Biceps curl',part:'Bicepsi'},
  {id:'e7',name:'Triceps extension',part:'Tricepsi'},
  {id:'e8',name:'Plank',part:'Trbuh'},
  {id:'e9',name:'Trčanje',part:'Kardio'},
  {id:'e10',name:'Veslanje',part:'Leđa'},
  {id:'e11',name:'Leg press',part:'Noge'},
  {id:'e12',name:'Dips',part:'Tricepsi'},
  {id:'e13',name:'Lateral raises',part:'Ramena'},
  {id:'e14',name:'Pull-up',part:'Leđa'},
  {id:'e15',name:'Sklekovi',part:'Grudi'},
  {id:'e16',name:'Bicikl',part:'Kardio'},
  {id:'e17',name:'Eliptični trenažer',part:'Kardio'},
  {id:'e18',name:'Plivanje',part:'Kardio'},
  {id:'e19',name:'Skipping',part:'Kardio'},
];

const DEFAULT_FOODS=[
  {id:'f1', name:'Piletina (belo meso)', unit:'g', protein:31, carbs:0, fat:3.6, kcal:165},
  {id:'f2', name:'Govedina', unit:'g', protein:26, carbs:0, fat:15, kcal:250},
  {id:'f3', name:'Jaje', unit:'kom', protein:6, carbs:0.6, fat:5, kcal:72},
  {id:'f4', name:'Skuta (svježi sir)', unit:'g', protein:11, carbs:3, fat:4, kcal:98},
  {id:'f5', name:'Mleko (2.8%)', unit:'ml', protein:3.4, carbs:4.8, fat:2.8, kcal:57},
  {id:'f6', name:'Jogurt (prirodni)', unit:'g', protein:3.5, carbs:4.7, fat:3.3, kcal:61},
  {id:'f7', name:'Ovsena kaša', unit:'g', protein:13, carbs:68, fat:7, kcal:389},
  {id:'f8', name:'Pirinač (beli)', unit:'g', protein:2.7, carbs:28, fat:0.3, kcal:130},
  {id:'f9', name:'Krompir', unit:'g', protein:2, carbs:17, fat:0.1, kcal:77},
  {id:'f10',name:'Pasta (kuvana)', unit:'g', protein:5, carbs:31, fat:1, kcal:158},
  {id:'f11',name:'Hleb (integralni)', unit:'g', protein:9, carbs:41, fat:3.4, kcal:247},
  {id:'f12',name:'Brokoli', unit:'g', protein:2.8, carbs:7, fat:0.4, kcal:34},
  {id:'f13',name:'Spanać', unit:'g', protein:2.9, carbs:3.6, fat:0.4, kcal:23},
  {id:'f14',name:'Banana', unit:'kom', protein:1.3, carbs:27, fat:0.4, kcal:105},
  {id:'f15',name:'Jabuka', unit:'kom', protein:0.5, carbs:25, fat:0.3, kcal:95},
  {id:'f16',name:'Narandža', unit:'kom', protein:1.2, carbs:15, fat:0.2, kcal:62},
  {id:'f17',name:'Bademi', unit:'g', protein:21, carbs:22, fat:49, kcal:579},
  {id:'f18',name:'Kikiriki puter', unit:'g', protein:25, carbs:20, fat:50, kcal:588},
  {id:'f19',name:'Maslinovo ulje', unit:'ml', protein:0, carbs:0, fat:14, kcal:119},
  {id:'f20',name:'Losos', unit:'g', protein:20, carbs:0, fat:13, kcal:208},
  {id:'f21',name:'Tunjevina (konzerva)', unit:'g', protein:26, carbs:0, fat:1, kcal:116},
  {id:'f22',name:'Protein prah (whey)', unit:'g', protein:25, carbs:3, fat:1.5, kcal:120},
  {id:'f23',name:'Kafa (crna)', unit:'ml', protein:0.3, carbs:0, fat:0, kcal:2},
  {id:'f24',name:'Voda', unit:'ml', protein:0, carbs:0, fat:0, kcal:0},
  {id:'f25',name:'Sok (narandža)', unit:'ml', protein:0.7, carbs:10, fat:0.2, kcal:45},
  {id:'f26',name:'Čokolada (tamna)', unit:'g', protein:5, carbs:46, fat:31, kcal:546},
  {id:'f27',name:'Sveže povrće (mešano)', unit:'g', protein:1.5, carbs:5, fat:0.2, kcal:25},
  {id:'f28',name:'Pasulj (kuvani)', unit:'g', protein:8.9, carbs:22, fat:0.5, kcal:127},
  {id:'f29',name:'Leblebija', unit:'g', protein:9, carbs:27, fat:2.6, kcal:164},
  {id:'f30',name:'Sir (gauda)', unit:'g', protein:25, carbs:0, fat:31, kcal:356},
];
